apiVersion: v1
kind: Namespace
metadata:
  name: lab
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod
  namespace: lab
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/restrict-chmod.json
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
